# Generated by Django 5.0.6 on 2024-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='josaa2016',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(max_length=128)),
                ('institute_type', models.CharField(max_length=128)),
                ('institute_name', models.CharField(max_length=128)),
                ('academic_program', models.CharField(max_length=128)),
                ('seat_type', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('open_rank', models.CharField(max_length=128)),
                ('close_rank', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='josaa2017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(max_length=128)),
                ('institute_type', models.CharField(max_length=128)),
                ('institute_name', models.CharField(max_length=128)),
                ('academic_program', models.CharField(max_length=128)),
                ('seat_type', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('open_rank', models.CharField(max_length=128)),
                ('close_rank', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='josaa2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(max_length=128)),
                ('institute_type', models.CharField(max_length=128)),
                ('institute_name', models.CharField(max_length=128)),
                ('academic_program', models.CharField(max_length=128)),
                ('seat_type', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('open_rank', models.CharField(max_length=128)),
                ('close_rank', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='josaa2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(max_length=128)),
                ('institute_type', models.CharField(max_length=128)),
                ('institute_name', models.CharField(max_length=128)),
                ('academic_program', models.CharField(max_length=128)),
                ('seat_type', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('open_rank', models.CharField(max_length=128)),
                ('close_rank', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='josaa2020',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(max_length=128)),
                ('institute_type', models.CharField(max_length=128)),
                ('institute_name', models.CharField(max_length=128)),
                ('academic_program', models.CharField(max_length=128)),
                ('seat_type', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('open_rank', models.CharField(max_length=128)),
                ('close_rank', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='josaa2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(max_length=128)),
                ('institute_type', models.CharField(max_length=128)),
                ('institute_name', models.CharField(max_length=128)),
                ('academic_program', models.CharField(max_length=128)),
                ('seat_type', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('open_rank', models.CharField(max_length=128)),
                ('close_rank', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='josaa2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(max_length=128)),
                ('institute_type', models.CharField(max_length=128)),
                ('institute_name', models.CharField(max_length=128)),
                ('academic_program', models.CharField(max_length=128)),
                ('seat_type', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('open_rank', models.CharField(max_length=128)),
                ('close_rank', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='josaa2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.CharField(max_length=128)),
                ('institute_type', models.CharField(max_length=128)),
                ('institute_name', models.CharField(max_length=128)),
                ('academic_program', models.CharField(max_length=128)),
                ('seat_type', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('open_rank', models.CharField(max_length=128)),
                ('close_rank', models.CharField(max_length=128)),
            ],
        ),
    ]
